// migrate((db) => {
//     const dao = new Dao(db)
//     const collection = dao.findCollectionByNameOrId("users")
//     const record = new Record(collection)
//     record.setUsername("u_" + $security.randomStringWithAlphabet(5, "123456789"))
//     record.setPassword("1234567890")
//     record.set("name", "John Doe")
//     record.set("email", "test@example.com")
//     dao.saveRecord(record)
// })