// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('failedLogin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('failedLogin', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1435, height: 1035 })
    await driver.findElement(By.linkText("Log In")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("test@example.com")
    await driver.findElement(By.id("password")).sendKeys("password")
    await driver.findElement(By.css(".bg-blue-500")).click()
  })
})
